package collector

import (
	"strings"
	"testing"
)

const sampleIptables = `# Generated by iptables-save v1.8.5 on Wed Jun 11 18:00:00 2026
*filter
:INPUT DROP [1234:567890]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [987:65432]
-A INPUT -i lo -j ACCEPT
-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
-A INPUT -p tcp -m tcp --dport 22 -j ACCEPT
COMMIT
# Completed on Wed Jun 11 18:00:00 2026
`

// Same ruleset, different timestamp and different packet/byte counters.
const sampleIptablesNoise = `# Generated by iptables-save v1.8.5 on Thu Jun 12 09:30:00 2026
*filter
:INPUT DROP [99:88]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [7:6]
-A INPUT -i lo -j ACCEPT
-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
-A INPUT -p tcp -m tcp --dport 22 -j ACCEPT
COMMIT
# Completed on Thu Jun 12 09:30:00 2026
`

const sampleNft = `table inet filter {
	chain input {
		type filter hook input priority filter; policy drop;
		iif "lo" accept
		ct state established,related accept
		tcp dport 22 accept
		counter packets 100 bytes 8400 drop
	}
	chain forward {
		type filter hook forward priority filter; policy drop;
	}
}
`

func TestCanonicalizeIptablesCountAndStability(t *testing.T) {
	canon, rules := canonicalizeIptables(sampleIptables)
	if rules != 3 {
		t.Errorf("rules = %d, want 3", rules)
	}
	// Comment/date lines must be gone; counters zeroed.
	if strings.Contains(canon, "Generated by") || strings.Contains(canon, "1234:567890") {
		t.Errorf("canonical still contains volatile content:\n%s", canon)
	}
	if !strings.Contains(canon, "[0:0]") {
		t.Error("expected zeroed counters")
	}
	// The noisy variant (different timestamp + counters) must hash identically.
	canon2, rules2 := canonicalizeIptables(sampleIptablesNoise)
	if rules2 != 3 {
		t.Errorf("noise rules = %d, want 3", rules2)
	}
	if hashRuleset(canon) != hashRuleset(canon2) {
		t.Error("counter/timestamp-only differences must not change the hash")
	}
}

func TestCanonicalizeNftCountAndCounterZeroing(t *testing.T) {
	canon, rules := canonicalizeNftables(sampleNft)
	if rules != 4 {
		t.Errorf("rules = %d, want 4 (3 accepts + 1 counter drop)", rules)
	}
	if strings.Contains(canon, "packets 100 bytes 8400") {
		t.Error("nft counters not zeroed")
	}
	if !strings.Contains(canon, "packets 0 bytes 0") {
		t.Error("expected zeroed nft counter")
	}
	// A counter-only change must not move the hash.
	noisy := strings.Replace(sampleNft, "packets 100 bytes 8400", "packets 7777 bytes 999999", 1)
	canon2, _ := canonicalizeNftables(noisy)
	if hashRuleset(canon) != hashRuleset(canon2) {
		t.Error("nft counter-only change must not change the hash")
	}
}

func TestCanonicalizeEmpty(t *testing.T) {
	canon, rules := canonicalizeNftables("")
	if canon != "" || rules != 0 {
		t.Errorf("empty nft → %q / %d, want empty/0", canon, rules)
	}
	if hashRuleset("") != "" {
		t.Error("empty ruleset must hash to empty string")
	}
}

const sampleIp6tables = `# Generated by ip6tables-save v1.8.5 on Wed Jun 11 18:00:00 2026
*filter
:INPUT DROP [12:34]
-A INPUT -i lo -j ACCEPT
-A INPUT -p ipv6-icmp -j ACCEPT
COMMIT
`

const sampleIptablesMultiTable = `*nat
:PREROUTING ACCEPT [0:0]
-A PREROUTING -p tcp --dport 80 -j REDIRECT --to-ports 8080
COMMIT
*filter
:INPUT DROP [0:0]
-A INPUT -i lo -j ACCEPT
COMMIT
`

const sampleNftMultiChain = `table ip4 nat {
	chain prerouting {
		type nat hook prerouting priority dstnat; policy accept;
		tcp dport 80 redirect to :8080
	}
}
table inet filter {
	chain input {
		type filter hook input priority filter; policy drop;
		tcp dport 22 accept
	}
}
`

func TestParseIptablesRules(t *testing.T) {
	rules := parseIptablesRules(sampleIptables, "ip4")
	if len(rules) != 3 {
		t.Fatalf("got %d rules, want 3", len(rules))
	}
	for i, r := range rules {
		if r.Table != "ip4 filter" {
			t.Errorf("rule %d table = %q, want %q", i, r.Table, "ip4 filter")
		}
		if r.Chain != "INPUT" {
			t.Errorf("rule %d chain = %q, want INPUT", i, r.Chain)
		}
	}
	// On-host order is preserved, and counters/headers are absent.
	if rules[0].Rule != "-A INPUT -i lo -j ACCEPT" {
		t.Errorf("rule 0 = %q", rules[0].Rule)
	}
	if rules[2].Rule != "-A INPUT -p tcp -m tcp --dport 22 -j ACCEPT" {
		t.Errorf("rule 2 = %q", rules[2].Rule)
	}
}

func TestParseIptablesRulesMultiTable(t *testing.T) {
	rules := parseIptablesRules(sampleIptablesMultiTable, "ip4")
	if len(rules) != 2 {
		t.Fatalf("got %d rules, want 2", len(rules))
	}
	if rules[0].Table != "ip4 nat" || rules[0].Chain != "PREROUTING" {
		t.Errorf("rule 0 = %q/%q, want ip4 nat/PREROUTING", rules[0].Table, rules[0].Chain)
	}
	if rules[1].Table != "ip4 filter" || rules[1].Chain != "INPUT" {
		t.Errorf("rule 1 = %q/%q, want ip4 filter/INPUT", rules[1].Table, rules[1].Chain)
	}
}

func TestParseIptablesRulesFamilyTagsKeepV4V6Distinct(t *testing.T) {
	// Mirror the collector: v4 and v6 are parsed separately so a -A INPUT in
	// each address family does not collide.
	rules := parseIptablesRules(sampleIptables, "ip4")
	rules = append(rules, parseIptablesRules(sampleIp6tables, "ip6")...)
	var v4, v6 int
	for _, r := range rules {
		switch r.Table {
		case "ip4 filter":
			v4++
		case "ip6 filter":
			v6++
		default:
			t.Errorf("unexpected table %q", r.Table)
		}
	}
	if v4 != 3 || v6 != 2 {
		t.Errorf("v4=%d v6=%d, want 3/2", v4, v6)
	}
}

func TestParseIptablesRulesEmpty(t *testing.T) {
	if r := parseIptablesRules("", "ip4"); r != nil {
		t.Errorf("empty input → %v, want nil", r)
	}
	if r := parseIptablesRules("   \n\n", "ip4"); r != nil {
		t.Errorf("whitespace input → %v, want nil", r)
	}
}

func TestParseNftablesRules(t *testing.T) {
	rules := parseNftablesRules(sampleNft)
	if len(rules) != 4 {
		t.Fatalf("got %d rules, want 4", len(rules))
	}
	for i, r := range rules {
		if r.Table != "inet filter" || r.Chain != "input" {
			t.Errorf("rule %d = %q/%q, want inet filter/input", i, r.Table, r.Chain)
		}
	}
	if rules[0].Rule != `iif "lo" accept` {
		t.Errorf("rule 0 = %q", rules[0].Rule)
	}
	// The counter statement is captured with its counter zeroed (hash parity).
	last := rules[3].Rule
	if !strings.Contains(last, "packets 0 bytes 0") || strings.Contains(last, "packets 100") {
		t.Errorf("counter not zeroed in rule text: %q", last)
	}
	// The empty forward chain and the "type … policy …;" lines never appear.
	for _, r := range rules {
		if strings.HasPrefix(r.Rule, "type ") {
			t.Errorf("policy declaration leaked as a rule: %q", r.Rule)
		}
	}
}

func TestParseNftablesRulesMultiChain(t *testing.T) {
	rules := parseNftablesRules(sampleNftMultiChain)
	if len(rules) != 2 {
		t.Fatalf("got %d rules, want 2", len(rules))
	}
	if rules[0].Table != "ip4 nat" || rules[0].Chain != "prerouting" {
		t.Errorf("rule 0 = %q/%q, want ip4 nat/prerouting", rules[0].Table, rules[0].Chain)
	}
	if rules[1].Table != "inet filter" || rules[1].Chain != "input" {
		t.Errorf("rule 1 = %q/%q, want inet filter/input", rules[1].Table, rules[1].Chain)
	}
}

func TestParseNftablesRulesEmpty(t *testing.T) {
	if r := parseNftablesRules(""); r != nil {
		t.Errorf("empty input → %v, want nil", r)
	}
}

func TestHashRulesetDeterministic(t *testing.T) {
	canon, _ := canonicalizeIptables(sampleIptables)
	h1 := hashRuleset(canon)
	h2 := hashRuleset(canon)
	if h1 == "" || h1 != h2 {
		t.Errorf("hash not deterministic/non-empty: %q vs %q", h1, h2)
	}
	if len(h1) != 64 {
		t.Errorf("expected 64-char hex SHA-256, got %d chars", len(h1))
	}
}
