package collector

import (
	"strings"
	"testing"
)

const sampleIptables = `# Generated by iptables-save v1.8.5 on Wed Jun 11 18:00:00 2026
*filter
:INPUT DROP [1234:567890]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [987:65432]
-A INPUT -i lo -j ACCEPT
-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
-A INPUT -p tcp -m tcp --dport 22 -j ACCEPT
COMMIT
# Completed on Wed Jun 11 18:00:00 2026
`

// Same ruleset, different timestamp and different packet/byte counters.
const sampleIptablesNoise = `# Generated by iptables-save v1.8.5 on Thu Jun 12 09:30:00 2026
*filter
:INPUT DROP [99:88]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [7:6]
-A INPUT -i lo -j ACCEPT
-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
-A INPUT -p tcp -m tcp --dport 22 -j ACCEPT
COMMIT
# Completed on Thu Jun 12 09:30:00 2026
`

const sampleNft = `table inet filter {
	chain input {
		type filter hook input priority filter; policy drop;
		iif "lo" accept
		ct state established,related accept
		tcp dport 22 accept
		counter packets 100 bytes 8400 drop
	}
	chain forward {
		type filter hook forward priority filter; policy drop;
	}
}
`

func TestCanonicalizeIptablesCountAndStability(t *testing.T) {
	canon, rules := canonicalizeIptables(sampleIptables)
	if rules != 3 {
		t.Errorf("rules = %d, want 3", rules)
	}
	// Comment/date lines must be gone; counters zeroed.
	if strings.Contains(canon, "Generated by") || strings.Contains(canon, "1234:567890") {
		t.Errorf("canonical still contains volatile content:\n%s", canon)
	}
	if !strings.Contains(canon, "[0:0]") {
		t.Error("expected zeroed counters")
	}
	// The noisy variant (different timestamp + counters) must hash identically.
	canon2, rules2 := canonicalizeIptables(sampleIptablesNoise)
	if rules2 != 3 {
		t.Errorf("noise rules = %d, want 3", rules2)
	}
	if hashRuleset(canon) != hashRuleset(canon2) {
		t.Error("counter/timestamp-only differences must not change the hash")
	}
}

func TestCanonicalizeNftCountAndCounterZeroing(t *testing.T) {
	canon, rules := canonicalizeNftables(sampleNft)
	if rules != 4 {
		t.Errorf("rules = %d, want 4 (3 accepts + 1 counter drop)", rules)
	}
	if strings.Contains(canon, "packets 100 bytes 8400") {
		t.Error("nft counters not zeroed")
	}
	if !strings.Contains(canon, "packets 0 bytes 0") {
		t.Error("expected zeroed nft counter")
	}
	// A counter-only change must not move the hash.
	noisy := strings.Replace(sampleNft, "packets 100 bytes 8400", "packets 7777 bytes 999999", 1)
	canon2, _ := canonicalizeNftables(noisy)
	if hashRuleset(canon) != hashRuleset(canon2) {
		t.Error("nft counter-only change must not change the hash")
	}
}

func TestCanonicalizeEmpty(t *testing.T) {
	canon, rules := canonicalizeNftables("")
	if canon != "" || rules != 0 {
		t.Errorf("empty nft → %q / %d, want empty/0", canon, rules)
	}
	if hashRuleset("") != "" {
		t.Error("empty ruleset must hash to empty string")
	}
}

func TestHashRulesetDeterministic(t *testing.T) {
	canon, _ := canonicalizeIptables(sampleIptables)
	h1 := hashRuleset(canon)
	h2 := hashRuleset(canon)
	if h1 == "" || h1 != h2 {
		t.Errorf("hash not deterministic/non-empty: %q vs %q", h1, h2)
	}
	if len(h1) != 64 {
		t.Errorf("expected 64-char hex SHA-256, got %d chars", len(h1))
	}
}
